### ISSUE TITLE
RightScript attachments with same filename not supported

### ISSUE THREAD

**Issue by flaccid** [rightscale/right_st#19]
It looks like attachments with the same name whether the script is the same or not will fail with 'already exists'.

My ST has several scripts with the same attachment. Will fail:

`ERROR: Failed to download all attachments: File attachments/rs_distro.sh already exists`

I think its safe to assume that if the filename is the same then just skip if the checksum is the same, if its not perhaps need to think about uniqueness. At the moment I can't download an ST because of this logical bug.

**Comment by flaccid** [comment]
Any chance of a solution/fix for this one soon? We actually don't use right_st at all because of common attachments e.g. https://github.com/flaccid/rightscripts/blob/master/attachments/rs_distro.sh

**Comment by psschroeter** [comment]
Fixed v1.4.0 by downloading duplicated attachments into separate subdirs based upon the script name if there happens to be a duplicate.

**Comment by flaccid** [comment]
Thanks @psschroeter !
