### ISSUE TITLE
Add an option to st download to specify rightscript download directory

### ISSUE THREAD

**Issue by drew-rightscale** [rightscale/right_st#21]
It would be good to have an option to specify a directory location to contain the rightscripts when downloading a ST. Upload already understands rightscript paths in the yml file.

This way if I specify:

 right_st st download --rs_path rightscripts "My Server Template"

                         This would download the server template yml file in the current directory and create a
                         rightscripts directory in the current directory.

If I then contain multiple server templates in a single directory, or my git repo, it would look cleaner and be more organized, i.e. all the rightscripts in one subfolder and all the yml files in the top directory.

FYI, I've already added the code. Not sure how you handle submissions.

root@drew-test:/tmp/drew/right_st_working# ./right_st st download --help
usage: right_st st download [<flags>] <name|href|id> [<path>]

Download a ServerTemplate and all associated RightScripts/Attachments to disk

Flags:
  -h, --help             Show context-sensitive help (also try --help-long and --help-man).
  -d, --debug            Debug mode
  -c, --config="/root/.right_st.yml"
                         Set the config file path.
  -a, --account=ACCOUNT  RightScale account name to use
  -v, --version          Show application version.
      --rs_path=RS_PATH  Download location for rightscripts and attachments

                         Note: The rightscript path is always relative to the server template path.

                         Example: right_st st download --rs_path rightscripts "My Server Template"

                         This would download the server template yml file in the current directory and create a
                         rightscripts directory in the current directory.

Args:
  <name|href|id>  Script Name or HREF or Id
  [<path>]        Download location

**Comment by douglaswth** [comment]
This was implemented with #28.
