### ISSUE TITLE
hg installed by mercurial is a missing dependency

### ISSUE THREAD

**Issue by lopaka** [rightscale/right_st#26]
On a clean install of go1.6.2, running `make depend` results in the following error:

`[ERROR]	Update failed for bitbucket.org/pkg/inflect: hg is not installed`

Manually installing `mercurial` installs `hg`. `make depend` should probably install this.

**Comment by douglaswth** [comment]
It doesn't install `git` or `subversion` either? That's just a Golang development dependency and it depends on what platform you are on how you install it. The purpose of `make depend` is to install the Go library dependencies only.
