### ISSUE TITLE
Cannot upload RightScript with no Inputs

### ISSUE THREAD

**Issue by JerkyTreats** [rightscale/right_st#46]
Inputs appear to be required to validate/upload RightScript metadata. I have a script that has no Inputs. 

Inputs with none defined:
```
# ---
# RightScript Name: foo
# Description: bar
# Inputs: 
# Attachments: []
# ...
```

_Shows: Inputs must be specified_

```
# ---
# RightScript Name: foo
# Description: bar
# Attachments: []
# ...
```

_Shows: Inputs must be specified_

Trying `Inputs: blank` or faking an input doesn't appear to work.

**Comment by douglaswth** [comment]
Since the metadata format is based on YAML, the metadata has to be valid YAML, the proper format for specifying no inputs is to specify an empty map/hash:

```bash
# ---
# RightScript Name: foo
# Description: bar
# Inputs: {}
# Attachments: []
# ...
```

**Comment by JerkyTreats** [comment]
Ah, thanks.
