### ISSUE TITLE
Config file required even if using environment variables

### ISSUE THREAD

**Issue by srpomeroy** [rightscale/right_st#72]
Not sure if this is a recent change or not, but when running right_st headless on a system that does not have a config set for right_st, it errors out even though I am using environment variables.

![image](https://user-images.githubusercontent.com/15660532/68499734-ec520600-0227-11ea-9fe8-9eb939813a21.png)

**Comment by douglaswth** [comment]
The `right_st config show` is only supposed to work with a config file. The other non-`config` commands seem to work fine with environment variables.

**Comment by srpomeroy** [comment]
It does not work for me
![image](https://user-images.githubusercontent.com/15660532/68503741-94200180-0231-11ea-8d25-b978a07477c6.png)

**Comment by douglaswth** [comment]
Ah ha! It is occurring only if you use password instead of refresh token.

**Comment by douglaswth** [comment]
I've run into some issues on Travis CI, but you can try the `right_st.exe` from the [AppVeyer build](https://ci.appveyor.com/project/RightScale/right-st/builds/28725024/artifacts).

**Comment by srpomeroy** [comment]
Confirmed, the AppVeyer build works!
